[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd ../.. && pnpm --filter @repo/common build",
  "cd ../.. && pnpm --filter @repo/db build",
  "cd ../.. && pnpm --filter @repo/ui build",
  "cd ../.. && pnpm --filter excelidraw-frontend build"
]

[start]
cmd = "pnpm start"
