version: '3.8'

services:
  excelidraw-frontend:
    build:
      context: .
      dockerfile: apps/excelidraw-frontend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_HTTP_BACKEND=http://localhost:3002
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    depends_on:
      - https-backend
      - ws-backend

  https-backend:
    build:
      context: .
      dockerfile: apps/https-backend/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  ws-backend:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
